version: '3.8'

services:
  proyecto-app:
    build:
      context: ./Proyecto
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://proyecto-db:3306/proyecto?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER_NAME: root
      DB_PASSWORD: DLSB2024diana
    restart: always
    volumes:
      - ./imagenesProyecto:/app/imagenesProyecto
    depends_on:
      proyecto-db:
        condition: service_healthy

  proyecto-db:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: DLSB2024diana
      MYSQL_PASSWORD: DLSB2024diana
      MYSQL_DATABASE: proyecto
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
